version: 2
defaults: &defaults
  docker:
    - image: ubuntu:19.10
jobs:
  build_linux:
    <<: *defaults
    environment:
      MAP: "denmark"
    steps:
      - checkout
      - run:
          name: Id
          command: cat /etc/*release
      - run:
          name: Setup requirements
          command: |
            apt-get update
            apt-get install -y libpng-dev libfreetype6-dev libdbus-glib-1-dev libgtk2.0-dev curl
            apt-get install -y libtool-bin libssl-dev autoconf wget
      - run:
          name: Build for Linux
          command: |
            export CFLAGS=" -finline-limit=1 -fkeep-inline-functions -O0 -DNO_GTYPES_ -DPLUGSSS -g -DONLY_C_BORDER -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -ldl -lpthread "
            export CFLAGS=" -DNAVIT_TRANS_LAT_LON_GEO_NOFUNCS -DMAPTOOL ""$CFLAGS" ;
            ./autogen.sh
            ls -la ../
            mkdir bin
            cd bin
            ../configure --disable-samplemap --disable-graphics-opengl --disable-svg --disable-svg2png --disable-binding-python --disable-fastmath --disable-gui-gtk --disable-gui-win32 --disable-gui-qml
            cd navit
            make
            make version.h
            cd maptool
            make
            ldd maptool
            ls -la
#            gcc --static -static -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -lpthread -Wall -Wcast-align -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wpointer-arith -Wreturn-type -D_GNU_SOURCE  -o maptool_linux64_static maptool.o -lglib-2.0 .libs/libmaptool.a -lgthread-2.0 -lgmodule-2.0 -ldl -lrt -lz ../.libs/libnavit.a -pthread -lgthread-2.0 -lrt -lglib-2.0 -pthread -lgmodule-2.0 -lrt -lglib-2.0 -lz p2t/.libs/libp2tc.a refine/.libs/libp2tc-refine.a libcfu-0.03-zanavi/src/libcfu.a -lm -lcrypto -ldl
      
      - run:
          name: Get OSM data
          command: |
            cd bin/navit/maptool
            wget -c -O map1.osm.bz2 http://download.geofabrik.de/europe/$MAP-latest.osm.bz2
            ls -la
          no_output_timeout: 120m
      - run:
          name: Convert map
          command: |
            cd bin/navit/maptool
            ls -la
            bzcat map1.osm.bz2 | ./maptool -o runtimes.sqlite -6 -k -n -U -S 500000000 map.bin
          no_output_timeout: 120m
      - run:
          name: split binfile
          command: |
            mkdir out
            ls -la
            cp bin/navit/maptool/map.bin.idx out/$MAP.bin.idx
            cp bin/navit/maptool/map.bin out/$MAP.bin
            ls -la
            ls -la out
      - store_artifacts:
          path: out
workflows:
  version: 2
  build_all:
    jobs:
      - build_linux
      
